#!/usr/bin/env python
# vim: ts=3 sw=3 ai
#
#  Test the configuration file, report any errors
#
#  Copyright (c) 2004-2007, Sean Reifschneider, tummy.com, ltd.
#  All Rights Reserved
#  <jafo@tummy.com>

import sys
from pprint import pprint
from tumgreyspfsupp import load_config

#  check arguments
if len(sys.argv) != 2:
	print 'ERROR: Configuration file must be specified as a command-line argument.'
	sys.exit(2)

# Try to load config to pretty print possible exceptions
try:
    execfile(sys.argv[1], {}, {})
except Exception, e:
    etype, value, tb = sys.exc_info()
    print '\nError reading config file "%s": %s\n' % (sys.argv[1], value)
    sys.exit(1)

config = load_config(filename=sys.argv[1], config={}, use_syslog=False, use_stderr=True)

print '\nConfiguration data:\n'
pprint(config._config)
print '\nConfig file "%s" successfully loaded.\n' % sys.argv[1]

sys.exit(1)
