#!/usr/bin/env python
#
#  Walk through the greylist directory and clean out old entries, based on
#  the values in the config file.
#
#  Copyright (c) 2004-2007, Sean Reifschneider, tummy.com, ltd.
#  All Rights Reserved
#  <jafo@tummy.com>

import sys, time
from tumgreyspfsupp import prepare_start

config, db = prepare_start(use_syslog=False, use_stderr=True)

entries = db.greylist.find()
    
for e in entries:
    expire_time = time.time() - (config['greylistExpireDays'] * 86400)
        
    # last_changed < allowed_from and now - allowed_from > (0.5 * day)
    # true if greylisted and never again tried and greylist entry is older then half a day
    expired_auth = e['changed'] < e['allowed_from'] and (time.time() - e['allowed_from']) > (12 * 3600)
    # true if changed more then expire_time days ago 
    expired_after_auth = e['changed'] < expire_time
        
    if expired_auth or expired_after_auth:
        db.greylist.remove({'_id': e['_id']})
        

