#!/usr/bin/env python
#
#  Display information about the entries in the greylist.
#
#  Copyright (c) 2004-2007, Sean Reifschneider, tummy.com, ltd.
#  All Rights Reserved
#  <jafo@tummy.com>

import sys, time
from collections import OrderedDict

import ipaddr

sys.path.append('/Users/jschrewe/webdesign/tumgreyspf')
from tumgreyspfsupp import prepare_start

config, db = prepare_start(use_syslog=False, use_stderr=True)

def prettysecs(seconds):
    seconds = int(seconds)
    
    negative = False
    if seconds < 0:
        negative = True
        seconds = seconds * -1
        
    secs = [
        (86400, 'd'),
        (3600, 'h'),
        (60, 'm'),
    ]
    for p_secs, p_descr in secs:
        if seconds > p_secs:
            time = seconds / p_secs
            if negative: time = time * -1
            return '%d%s' % (time, p_descr)
                
    return '%ss' % seconds

entries = db.greylist.find()
data = {}
for e in entries:
    expire_time = time.time() - (config['GREYLISTEXPIREDAYS'] * 86400)
    now = time.time()
    
    stats = []
    if e['changed'] < e['allowed_from']:
        stats.append('Blocked')
    if e['allowed_from'] > now:
        stats.append('Pending')
        
    if len(stats) > 0:
        stats = '(%s)' % ', '.join(stats)
    else:
        stats = ''
    
    ip = ipaddr.ip_address(e['client_ip'])
    
    data[ip] = {
        'ip': ip,
        'sender': e['sender'],
        'recipient': e['recipient'],
        'allowed_from': prettysecs(now - e['allowed_from']),
        'last': prettysecs(now - e['changed']),
        'expires': prettysecs(e['changed'] - expire_time),
        'stats': stats,
    }


ordered_data = OrderedDict(sorted(data.items(), key=lambda item: item[0]))

for i in ordered_data.itervalues():
    if i['allowed_from'][0] == '-':
        in_or_since = 'IN'
        i['allowed_from'] = i['allowed_from'][1:]
    else:
        in_or_since = 'SINCE'
        
    print 'IP: %s\t%s\n    SENDER: %s\n    RECIPIENT: %s\n    ALLOWED %s: %s\n    LAST SEEN: %s\n    EXPIRES IN: %s\n' % (
        i['ip'],
        i['stats'],
        i['sender'], 
        i['recipient'],
        in_or_since,
        i['allowed_from'],
        i['last'],
        i['expires'],
    )
