#!/usr/bin/env python
# vim: ts=3 sw=3 ai
#
#  Test the configuration file, report any errors
#
#  Copyright (c) 2004-2007, Sean Reifschneider, tummy.com, ltd.
#  All Rights Reserved
#  <jafo@tummy.com>
#
#  Jan Schrewe <jan@schafproductions.com>, 2012

import sys
from pprint import pformat
from tumgreyspfsupp import load_config

# Try to load config to pretty print possible exceptions
try:
    execfile(sys.argv[1], {}, {})
except Exception, e:
    etype, value, tb = sys.exc_info()
    print '\nError reading config file "%s": %s\n' % (sys.argv[1], value)
    sys.exit(1)

config = load_config(config={}, use_syslog=False, use_stderr=True)

print '\nConfiguration data:\n'
for k, v in config:
    if k in ['spfwhitelist', 'greylistwhitelist',]:
        print "%s: %s" % (k, str(v))
    else:
        print "%s: %s" % (k, pformat(v))
print '\nConfig file "%s" successfully loaded.\n' % sys.argv[1]

sys.exit(1)
