#!/usr/bin/env python
#
#  Walk through the greylist directory and clean out old entries, based on
#  the values in the config file.
#
#  Copyright (c) 2004-2007, Sean Reifschneider, tummy.com, ltd.
#  All Rights Reserved
#  <jafo@tummy.com>
#
#  Jan Schrewe <jan@schafproductions.com>, 2012

import sys
from time import time
from tumgreyspfsupp import prepare_start

config = prepare_start(use_syslog=False, use_stderr=True)

HALF_DAY = 12 * 3600
expire_days = config['greylistExpireDays'] * 86400

entries = config.db.greylist.find()

for e in entries:
    # last_changed < allowed_from and now - allowed_from > (0.5 * day)
    # true if greylisted and never again tried and greylist entry is older then half a day
    greylisted = e['changed'] < e['allowed_from']
    allowed_since = time() - e['allowed_from']
    expired_auth = greylisted and allowed_since > HALF_DAY
    
    # true if changed more then expire_time days ago
    expire_time = time() - expire_days 
    expired_after_auth = e['changed'] < expire_time
        
    if expired_auth or expired_after_auth:
        config.db.greylist.remove({'_id': e['_id']})
        

